### ISSUE TITLE
Direct Connection from MPS to AMT

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/mps#10]
As an ISV, I want to be able to deploy the MPS to an enterprise network and manage AMT devices directly, without using the CIRA channel

**Comment by acveigas** [comment]
I have the same requirement. We have few customers who have Intel AMT devices with Static IP. CIRA doesn't work with Static IP, hence the next best approach is direct connect. @matt-primrose

**Comment by matt-primrose** [comment]
Strategic direction moving away from local network management.  Closing this issue.  If this request is raised again, can look at re-opening this issue.
