### ISSUE TITLE
Sleep and Hibernate power action commands are not working.

### ISSUE THREAD

**Issue by Nader-FIT** [open-amt-cloud-toolkit/mps#1000]
**Describe the bug** 🪲
We are having trouble sending the Sleep and Hibernate power actions. We identified this problem when we tried to run these commands in our application that uses the AMT Cloud Toolkit. Basically we send the Sleep action and the machine remains on, and when we send the Hibernate command, the machine is turned off.

**To Reproduce** 🪜
1. We connect the machine with the AMT CLOUD,
2. Click on Hibernate in the toolkit interface and it performs the power down action

**Expected behavior**
Have him run the Hibernate command on the machine

**Screenshots** 🖼️
As you can see in the log, the history shows that power action 8, which is the power down, was executed, but we were clicking on Hibernate
![image](https://github.com/open-amt-cloud-toolkit/mps/assets/141176476/78d02643-05dc-4175-842a-858b583fa6ea)

**AMT Device (please complete the following information):** 🖥️
We did the tests on 4 machines, and on 3 of them this happened
 - OS: Windows 11 64 Pro
 - AMT Version: 16.1.25
 - AMT Configuration Mode: Client Control Mode
 - Network Configuration: Dynamic IP
-------------------------------------------------
- OS: Windows 11 64 Pro
 - AMT Version: 15.0.42
 - AMT Configuration Mode: Admin Control Mode
 - Network Configuration: Dynamic IP
-------------------------------------------------
- OS: Windows 10 64
 - AMT Version: 11.8.92
 - AMT Configuration Mode: Client Control Mode
 - Network Configuration: Dynamic IP

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: Azure
 - Node Version: 16.18.1 (LTS)
 - Component & Version: MPS 2.7 and 2.11

**Comment by bwendlandt-intel** [comment]
Hello!

The 4 options listed, including Sleep and Hibernate, require an in-band (i.e. OS-level) agent running to perform these actions since these are OS-implemented power actions.  At a basic level, AMT can accept these requests, but must hand them off to the OS to actually perform.

Can you confirm that you have an in-band agent running?  This would be different from RPC.  A very common example would be Intel Local Management Service (LMS).  This is commonly preinstalled on many OEM Windows-based devices.  However, it may not be installed in different situations like if a OEM device was wiped entirely or on Linux devices.

On Windows, you can verify it is running via Services:
![image](https://github.com/open-amt-cloud-toolkit/mps/assets/74682355/ff76910f-ce46-4bac-ac6b-629584da1657)

**Comment by bwendlandt-intel** [comment]
Some additional info on your note about the audit log.

#8 translates to 'Remote Hibernate Initiated'. not Power Down.  This number returned is actually a combination of IDs returned from the AMT FW that MPS tries to interpret and return as user readable logs.  A full list of the converted codes can be found in `/mps/src/utils/constants.ts`, if curious.

```
1708: 'Remote Hibernate initiated',
```

When looking at the call using Chrome Dev Tools, you should be able to verify the correct power action is sent.

![image](https://github.com/open-amt-cloud-toolkit/mps/assets/74682355/6dd516fc-72f7-408b-8a2b-1ff15e6c058f)

<br>
Within the Audit Log call, you can also see how the 1708 number is built based off AuditAppID and EventID.  It looks like the team has added the correct Hibernate ID conversion in newer versions of MPS starting with v2.10.1 or newer. See #949 

![image](https://github.com/open-amt-cloud-toolkit/mps/assets/74682355/d39e9883-0f7a-440b-8010-b735beb94a36)


<br>
Hopefully that helps clear some of that confusion as well!

**Comment by Nader-FIT** [comment]
Hello everything is fine? So I checked and the LMS is installed and running correctly.

Below is the print of the request and the response that was sent.
![image](https://github.com/open-amt-cloud-toolkit/mps/assets/141176476/760d42e3-e26b-45ca-95de-b06a90a25ef9)
![image](https://github.com/open-amt-cloud-toolkit/mps/assets/141176476/e070ccd4-a5ab-40d5-95f5-ffe8aa3ef57c)

I'll send the json too if it can be useful.

{method: "PowerAction", action: 7, useSOL: false}

{
    "Header": {
        "To": "http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous",
        "RelatesTo": 0,
        "Action": "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_PowerManagementService/RequestPowerStateChangeResponse",
        "MessageID": "uuid:00000000-8086-8086-8086-0000000000C4",
        "ResourceURI": "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_PowerManagementService"
    },
    "Body": {
        "ReturnValue": 0,
        "ReturnValueStr": "SUCCESS"
    }
}

And a print of the Audit Log as well. Remembering that when I sent the Hibernate command, the machine had Power Status Off.
![image](https://github.com/open-amt-cloud-toolkit/mps/assets/141176476/12114ce5-100a-4542-a4b8-e88a2233a162)

**Comment by bwendlandt-intel** [comment]
> And a print of the Audit Log as well. Remembering that when I sent the Hibernate command, the machine had Power Status Off.

These commands will only successfully execute if the OS is running and operational because these are OS actions, not AMT.  Thus, the device must be powered on, before running the commands.

Because Hibernate is not supported on all devices (due to OS restrictions), it might be good to also verify if these devices are capable of it.  Or if it might have to be enabled in Power & Sleep Settings within Windows.
<br>
The API call and Audit Log look to be executing correctly, so I would wager this has something to do with how the individual device settings and configurations.

**Comment by brunomirandades** [comment]
Hello there!

We've revisited this issue using the latest toolkit versions and tested it on the same devices mentioned in the original post. Here's what we observed:

1. Hibernate action: It appears to be working correctly for all three tested devices. No issues with hibernate anymore.

2. Sleep action: However, there seems to be an unusual behavior with the sleep action. For a couple of these devices, it's triggering a warning in the toolkit sample UI that reads "POWER ACTION SENT BUT IS NOT READY." On the other hand, at least one device successfully executes the sleep command. We suspect that this behavior may be related to the available sleep states on each machine. The device where the sleep command works has Sleep Mode S3, which others do not have. Could these differences in sleep states be causing the issue? If so, what do these differences signify? It's worth noting that manually setting the sleep action through the Windows Start menu works as expected on all devices.

Below, you'll find:

* A screenshot of the sample UI displaying the warning for a non-working sleep action and also command prompt output regarding the available sleep states for these very machines (they are similar to each other).

![imagem](https://github.com/open-amt-cloud-toolkit/mps/assets/60761724/494e1b8d-cc52-4e22-88c6-d881f0dfa0ff)

```
>powercfg /availablesleepstates
The following sleep states are available in this system:
	Sleep (S0 Idle with Low Power Consumption) Connected via Network
	Hibernate
	Fast Startup

The following sleep states are not available in this system:
	Sleep Mode (S1)
		The system firmware does not support this sleep state.
		This sleep mode is disabled when there is no support for the low-power idle state of S0.
	Sleep Mode (S2)
		The system firmware does not support this sleep state.
		This sleep mode is disabled when there is no support for the low-power idle state of S0.
	Sleep Mode (S3)
		The system firmware does not support this sleep state.
		This sleep mode is disabled when there is no support for the low-power idle state of S0.
		The current Device Guard configuration has disabled this sleep state.
	Hybrid Suspension
		Sleep Mode (S3) is not available.
		The hypervisor does not support this sleep mode.
```

* A command prompt output regarding the available sleep states for the machine where the sleep action is working.

```
>powercfg /availablesleepstates
The following sleep states are available in this system:
	Sleep (S3)
	Hibernate
	Hybrid Suspension
	Fast Startup

The following sleep states are not available in this system:
	Sleep Mode (S1)
		The system firmware does not support this sleep state.
	Sleep Mode (S2)
		The system firmware does not support this sleep state.
	Sleep (S0 Idle with Low Power Consumption)
		The system firmware does not support this sleep state.
```

Please keep in mind that both of these prompt messages were roughly translated from PT-BR, so they may not be entirely accurate.
