### ISSUE TITLE
Bug: Custom middleware example overwrites tenantId with empty string

### ISSUE THREAD

**Issue by fmiu-imperosoftware** [open-amt-cloud-toolkit/mps#1020]
Bug in 2.13!

We've upgraded  from 2.8 to 2.13.

The custom middleware example set tenantId = ''. 
https://github.com/open-amt-cloud-toolkit/mps/blob/main/src/middleware/custom/example.ts#L19

Our tenantId middleware is named **connect-portal-tenant-id.js**. Linux lists files in alphabeticaly order so **example.ts** will come after ours and overwrite the tenantId on request. As a result the multi tenant feature does not work anymore!

The line above should be commented, it's not good to provide an example middleware that alters the flow.

**Comment by bwendlandt-intel** [comment]
Hi! I would advise to just delete the example file.  The intention for folks implementing multitenancy is to either overwrite or delete `example.ts`.  We can be more clear on that through comments/documentation.

Unfortunately, we do not have plans to remove and/or comment out Line 19 from `example.ts`.  This file and line is required to continue support for **non**-multitenant deployments.

The team revisited our discussion from when this was originally decided. The removal of this would require a number of MPS/RPS changes that intertwines multitenancy much tighter to our services.  In trying to stay as true as we can to service and feature modularization, we want to keep all handling of multitenancy exclusively to the middleware.

Please let us know if you have any more thoughts/questions around this, or I will close these issues. Thanks!

(Linking https://github.com/open-amt-cloud-toolkit/rps/issues/1148 to here too)
