### ISSUE TITLE
AMT 12 dropping CIRA when sending command while system is off

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/mps#196]
Toolkit version: 1.3
AMT device version: 12
Steps to reproduce:

1. Send AMT command to power off system (either REST call or through UI)
2. Once device is off, send any other command (get powerstate, refresh device page on the UI and re-pull hardware)
3. In MPS logs, will see the device disconnect and be removed after several seconds

Sometimes the device will reconnect after a minute or two, other times you need to completely power off the device (pull power or 5 second hold on the power button).  Once you power the device back on, it will reconnect to MPS.

Have tested this on other AMT versions (11.8) and this behavior doesn't happen.

**Comment by vyshali-chitikeshi** [comment]
Vyshali needs to test with AMT 12 system and see if issue is reproducible.

**Comment by vyshali-chitikeshi** [comment]
Not able to replicate the issue on latest FW systems using v 1.5 release.
