### ISSUE TITLE
MPS CIRA connection not working

### ISSUE THREAD

**Issue by acveigas** [open-amt-cloud-toolkit/mps#2]
* MPS CIRA connection not working on Node v8.11.4 & npm v5.6.0
* All the other functionality of project like REST API's, Web UI etc working fine
* AMT device doesn't initiate CIRA on above mentioned Node version for some reason

**Comment by graikhel-intel** [comment]
Hi @acveigas 
There was an issue with express-ws library (ws.pause definition to be specific) which had to be updated. The latest master should not have any connection issues.
