### ISSUE TITLE
Audit Log calls never respond on specific versions of AMT

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/mps#301]
On specific versions of AMT, the Audit Log REST API call will fail to respond.  In the Sample UI this manifests as the Device page never loading any device information.  Currently we are seeing this on a couple of different versions of AMT (11.6.10, 12.0.40).  Updating the AMT FW to the latest version resolves this issue.

**Comment by rsdmike** [comment]
This is also an issue on AMT 15, where paging is causing a problem with startIndex=0, this seems MPS specific, and not AMT specific.

**Comment by vyshali-chitikeshi** [comment]
No longer reproducible.
