### ISSUE TITLE
Incorrect/Incomplete REST API Documentation for RPS

### ISSUE THREAD

**Issue by sedillo** [open-amt-cloud-toolkit/mps#33]
1. The documented endpoints are incorrect and missing admin directory
https://open-amt-cloud-toolkit.github.io/mps/APIs/RPSmethods/ciraconfig/#get-all-cira-configurations
https://open-amt-cloud-toolkit.github.io/mps/APIs/RPSmethods/ciraconfig/#get-a-cira-configuration
https://open-amt-cloud-toolkit.github.io/mps/APIs/RPSmethods/ciraconfig/#create-a-cira-configuration

For example:
Documented Endpoint: /api/v1/ciraconfigs/
Actual Endpoint: /api/v1/**admin**/ciraconfigs

2. I'm assuming this is POST method, but it should probably be documented.
https://open-amt-cloud-toolkit.github.io/mps/APIs/RPSmethods/ciraconfig/#create-a-cira-configuration

3. Error using Postman Google Chrome extension with POST methods
Error: rps_1  | (node:54) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'configName' of undefined
Getting a similar errors as above for these endpoints:
    /api/v1/admin/ciraconfigs/create
    /api/v1/admin/profiles/create

**Comment by matt-primrose** [comment]
Hi @sedillo 

Can you attach the payload you used when you got the error using Postman?

Thanks!
-Matt

**Comment by bwendlandt-intel** [comment]
As far as the documentation feedback goes, this set of changes are now grouped with some others planned for early Monday.

Thanks,
BW

**Comment by sedillo** [comment]
Good to meet you @matt-primrose 

These are the two postman queries I am trying

#### 1. Create RPS Profile:
URL: https://\<IP\>:8081/api/v1/admin/profiles/create
Header: X-RPS-API-Key=\<KEY\>
Payload:
```
{
    "payload" :  
    {
        "profileName": "postman-profile",
        "amtPassword":"P@ssw0rd",
        "generateRandomPassword": "false",
        "passwordLength": 8,
        "ciraConfigName": "testConfig",
        "activation": "ccmactivate"
    }
}
```
RPS Server Error:
```
rps_1  | (node:51) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'generateRandomPassword' of undefined
rps_1  |     at readBody (/rcs-microservice/dist/routes/admin/profiles/createProfile.js:68:29)
rps_1  |     at /rcs-microservice/dist/routes/admin/profiles/createProfile.js:20:27
rps_1  |     at Generator.next (<anonymous>)
rps_1  |     at /rcs-microservice/dist/routes/admin/profiles/createProfile.js:8:71
rps_1  |     at new Promise (<anonymous>)
rps_1  |     at __awaiter (/rcs-microservice/dist/routes/admin/profiles/createProfile.js:4:12)
rps_1  |     at createProfile (/rcs-microservice/dist/routes/admin/profiles/createProfile.js:17:12)
rps_1  |     at Layer.handle [as handle_request] (/rcs-microservice/node_modules/express/lib/router/layer.js:95:5)
rps_1  |     at next (/rcs-microservice/node_modules/express/lib/router/route.js:137:13)
rps_1  |     at Route.dispatch (/rcs-microservice/node_modules/express/lib/router/route.js:112:3)
rps_1  | (node:51) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
```
#### 2. Create CIRA Profile:
URL: https://\<IP\>:8081/api/v1/admin/ciraconfigs/create
Header: X-RPS-API-Key=\<KEY\>
Payload:
```
{
    "payload": {
        "configName": "config1",
        "mpsServerAddress": "<IP>",
        "mpsPort": 4433,
        "username": "standalone",
        "password": "P@ssw0rd",
        "commonName": "<IP>",
        "serverAddressFormat": 201,
        "mpsRootCertificate": "",
        "proxyDetails": "", 
        "authMethod": 2
    }
}
```
RPS Server Error:
```
rps_1  | (node:51) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'configName' of undefined
rps_1  |     at readBody (/rcs-microservice/dist/routes/admin/ciraconfig/createCiraConfig.js:65:38)
rps_1  |     at /rcs-microservice/dist/routes/admin/ciraconfig/createCiraConfig.js:20:28
rps_1  |     at Generator.next (<anonymous>)
rps_1  |     at /rcs-microservice/dist/routes/admin/ciraconfig/createCiraConfig.js:8:71
rps_1  |     at new Promise (<anonymous>)
rps_1  |     at __awaiter (/rcs-microservice/dist/routes/admin/ciraconfig/createCiraConfig.js:4:12)
rps_1  |     at createCiraConfig (/rcs-microservice/dist/routes/admin/ciraconfig/createCiraConfig.js:17:12)
rps_1  |     at Layer.handle [as handle_request] (/rcs-microservice/node_modules/express/lib/router/layer.js:95:5)
rps_1  |     at next (/rcs-microservice/node_modules/express/lib/router/route.js:137:13)
rps_1  |     at Route.dispatch (/rcs-microservice/node_modules/express/lib/router/route.js:112:3)
rps_1  | (node:51) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
```

**Comment by madhavilosetty-intel** [comment]
@sedillo  - I am able to create a CIRA  config and AMT profile with the given payload. Can you please make sure that your postman is configured as given in the attachments and let us know if you are still seeing the issue?

**Header Info:** 

![Screenshot 2020-12-07 161451](https://user-images.githubusercontent.com/14915667/101420638-7a734280-38a7-11eb-8571-0a5a0e2cc749.png)

**Body:** 

![Screenshot 2020-12-07 155922](https://user-images.githubusercontent.com/14915667/101420628-7515f800-38a7-11eb-9ae6-f1694026d437.png)
