### ISSUE TITLE
Cannot send request through MPS API

### ISSUE THREAD

**Issue by imgonewild** [open-amt-cloud-toolkit/mps#349]
After installing docker-open-amt-cloud-toolkit V1.5. According to https://open-amt-cloud-toolkit.github.io/docs/1.5/APIs/indexMPS/ ,I was trying to send request to my AMT device, but when I used Postman to send POST request
``` json
{
 "username":"my user name",
 "password":"my password"
} 
```
to https://192.168.xxx.xxx/mps/api/v1/authorize
It showed up `{"message":"Unauthorized"}`

Also, 
when I used Postman to send POST request
``` json
{
 "action": 8,
 "userSOL":false
} 
``` 
to https://192.168.xxx.xxx/mps/api/v1/amt/power/action/MY_GUID
It showed up `{"message":"Unauthorized"}`

**Comment by madhavilosetty-intel** [comment]
It should be https://192.168.xxx.xxx/mps/login/api/v1/authorize . Please refer to the docs https://open-amt-cloud-toolkit.github.io/docs/1.5/APIs/indexMPS/
