### ISSUE TITLE
Use database abstraction/ORM layer to support multiple SQL-based database

### ISSUE THREAD

**Issue by joko-sastriawan** [open-amt-cloud-toolkit/mps#360]
Current MPS database backend is hardcoded to PostgreSQL. As deployments environment varies, connecting to different database means intrusive code editing. In order to ease the adjustment to various deployment condition, database middleware such as knex, sequelize, bookshelf etc  should be looked at to provide flexibility.

**Comment by rsdmike** [comment]
Documentation will be provided and updated here:  https://github.com/open-amt-cloud-toolkit/docs/pull/64

**Comment by rsdmike** [comment]
The linked PR won't solve this, but puts us in the right direction
