### ISSUE TITLE
CIRA connection getting dropped randomly

### ISSUE THREAD

**Issue by shubh293** [open-amt-cloud-toolkit/mps#441]
Mostly, CIRA connection timeout trigger occurs when we use power action API like (power off, restart, power on bios). Because of this we lose connection on MPS but AMT is still sending keep alive request in every 30 seconds but on MPS side we have already closed CIRA connection of client and it is stuck in loop now, The client thinks that it is still connected but on the other side (MPS) we have already closed the connection.

I have to restart MPS server every time to get it working again.

**Comment by matt-primrose** [comment]
Hi @shubh293 
Can you provide some additional information for us?

- MPS Version
- AMT Version including full version string xx.xx.xx

Thanks!

**Comment by graikhel-intel** [comment]
@matt-primrose, I'm working with @shubh293 to root cause this issue. Seems like a race condition where MPS closes CIRA socket on timeout but AMT keeps sending keepalive on the socket.
