### ISSUE TITLE
Unable to view hostname in the MPS once the AMT device gets registered

### ISSUE THREAD

**Issue by abinashdtt45** [open-amt-cloud-toolkit/mps#53]
We registered the AMT device with MPS using the RPC. We don't see the AMT device name in the MPS dashboard; rather we see the UUID as the name as well as the uuid for the device. To identify a device , it is difficult to do that with the uuid if say 100 devices are registered.

**Comment by rsdmike** [comment]
Hey @abinashdtt45, this is something we've talked about as an issue and will address in a future release. We'll track this feature in our backlog. Thanks!

**Comment by rsdmike** [comment]
This is available in v1.2.0
