### ISSUE TITLE
MPS should wait for vault to be unsealed - CIRA connections fail

### ISSUE THREAD

**Issue by orinem** [open-amt-cloud-toolkit/mps#614]
**Describe the bug** 🪲
MPS will create new certificates if the vault is sealed.  Incoming CIRA connections will fail due to expecting the old certificate.

**To Reproduce** 🪜

[Follow steps to run vault in production mode here](https://open-amt-cloud-toolkit.github.io/docs/2.3/Reference/productionVault/)

Create a profile with a CIRA config and provision machines using it.

Restart Docker containers from Docker Desktop.

Unseal the vault.

Machines will show RAS Remote Status of "connecting" forever and the Web UI will show the machines as disconnected.

**Expected behavior**

Machines reconnect with CIRA.

**AMT Device (please complete the following information):** 🖥️
 
N/A

**Service Deployment (please complete the following information):** ⛈️
 Docker, openamt 2.3.1

**Additional context**

Relevant part of MPS log:

```
2022-05-13T17:07:09.127Z error: getSecretAtPath MPSCerts error : Response code 503 (Service Unavailable)
2022-05-13T17:07:09.128Z info: Generating Root certificate...
2022-05-13T17:07:09.436Z info: Generating Intel AMT MPS certificate...
2022-05-13T17:07:09.571Z error: Error while writing secrets : Response code 503 (Service Unavailable)
2022-05-13T17:07:09.596Z info: Intel(R) AMT server running on 10.0.0.193:4433.
2022-05-13T17:07:09.596Z info: MPS Microservice running on 10.0.0.193:3000.
2022-05-13T17:20:07.188Z info: MQTT client closed

<restart MPS container>

2022-05-13T17:20:08.885Z info: Intel(R) AMT server running on 10.0.0.193:4433.
2022-05-13T17:20:08.886Z info: MPS Microservice running on 10.0.0.193:3000.
```

When MPS starts, it attempts to get the certificates from the vault.  It gets a 503 response indicating the vault is sealed.  It treats this response the same as if no certificates exist in the vault (the response is 404 if the certificates do not exist in the vault) and creates new certificates.

Machines connecting CIRA don't like the new certificates and the connections fail.

**Workaround**

Always restart MPS container after unsealing the vault and don't do anything involving MPS while the vault is sealed (creating CIRA profiles for example).  MPS will revert to using the certificates stored in the vault after the restart.

I'm not familiar enough with how MPS is listening for connections to definitively suggest a fix.  Perhaps reject connections while the vault is sealed?  Once unsealed, get the certificates or create new certificates on a 404 response.  Check vault on a timer or on incoming connections?

There may be other timing windows where MPS will serve certificates which have not been stored in the vault that can occur during the vault setup process.  I recommend restarting MPS before creating CIRA profiles as the certificate currently in use by MPS will be stored in the database for the profile and sent to machines during CIRA configuration!  This configuration will fail after MPS is restarted.

**Comment by orinem** [comment]
I suppose the title might better be something like: "MPS should wait for secrets to be available before automatically creating certificates".

This is a problem with the order the services are started and particularly the need to unseal the vault if using Hashcorp Vault.  It may not normally be a problem with other secrets providers, but nothing is up 100% of the time so it's probably best to differentiate between "secrets not available" (server down, vault sealed, internet connectivity problems) and secret not found (nothing stored in the provider).

**Comment by rsdmike** [comment]
Hey @orinem, yup, the service should wait /retry until service is up. We'll add this to our backlog.

**Comment by matt-primrose** [comment]
Linked PR merged
