### ISSUE TITLE
Strange compilation errors

### ISSUE THREAD

**Issue by orinem** [open-amt-cloud-toolkit/mps#657]
After some combination of npm installs and deleting package-lock.json, both powerAction.ts and powerCapabilities.ts failed to compile.  In both cases, it was attempting to return a value from a function declared as returning Promise&lt;void&gt;.

```
mps % npm run build

> @open-amt-cloud-toolkit/mps@2.4.0 build
> tsc

src/routes/amt/powerAction.ts:24:5 - error TS2322: Type 'Response<any, Record<string, any>>' is not assignable to type 'void'.

24     return res.status(200).json(powerAction).end()
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/routes/amt/powerCapabilities.ts:21:5 - error TS2322: Type 'Response<any, Record<string, any>>' is not assignable to type 'void'.

21     return res.status(200).json(bootCaps).end()
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  src/routes/amt/powerAction.ts:24
     1  src/routes/amt/powerCapabilities.ts:21
```

The fix, should this occur, is either to remove the 'return' keyword or move it to a new line in these two files (falling through would simply return in both cases, but probably better to make it explicit).

After restoring my package-lock.json, this problem is no longer reproducible.

However, one of the fixes should be applied as trying to return something when void is expected doesn't make sense.

**Comment by rsdmike** [comment]
This is likely due to the upgrade to a newer version of typescript. We'll address shortly.
