### ISSUE TITLE
Some issues related to amt event logs

### ISSUE THREAD

**Issue by bberbel1-lenovo** [open-amt-cloud-toolkit/mps#794]
Hello there.

I have a few things to point out about the api/v1/amt/log/event/{guid} API call and documentation.

First of all I would like to ask if I am following the correct documentation (because some of the issues to be pointed out can be explained if not)

The initial link provided on the toolkit doc it this:
https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=HTMLDocuments%2FWS-Management_Class_Reference%2FAMT_EventLogEntry.htm

And following the docs and looking for the PET specs to translate the fields I got this:
https://www.intel.com/content/dam/www/public/us/en/documents/product-briefs/platform-event-trap.pdf

It seems to be an old document but I did not found anything newer related to this. Is this the right place I should be looking for to translate those event fields?

Anyway putting that aside there are a few issues I would like to point out here:
1. The API documentation: https://open-amt-cloud-toolkit.github.io/docs/2.7/APIs/indexMPS/ have a few key points that are misleading
1.1 All result event fields on the doc are lowercase but when we call the API all those fields starts with a Uppercase letter.
1.2 The field time is actually TimeStamp when calling the API
1.3 This is only a issue if the PET document pdf I pointed out is the right one but on the sample value and also calling the API the entity: 34 is returning the entityStr: "BIOS", but looking at the documentation BIOS should be 35. 
As I checked on the code for this it seems that the part that does not match between that doc and the current enum used is actually the number 19 (it was marked as reserved on the doc). On the current code we can find it here:
https://github.com/open-amt-cloud-toolkit/mps/blob/88a14f4b67385f922a48570fada901d257bd9e71/src/utils/constants.ts
Checking for SystemEntityTypes

Note: For the first two issues I don't know if the right place to post would be here or on the sample UI repo.

**Comment by graikhel-intel** [comment]
Hi @bberbel1-lenovo,

1.1 and 1.2 definitely seem to be documentation issues. Typically we log documentation issues under https://github.com/open-amt-cloud-toolkit/docs but no problem, we will work on getting these issues fixed.

I've reached out to our firmware team internally to see if [this](https://www.intel.com/content/dam/www/public/us/en/documents/product-briefs/platform-event-trap.pdf) is the latest PET specification document. 

Regarding 1.3, this seems like a bug too (acc to PET spec document) but will update this thread once I hear from the firmware team.

**Comment by bberbel1-lenovo** [comment]
Hello @graikhel-intel 

Thank you for the fast response. I will be waiting for further updates on this issue them.

**Comment by graikhel-intel** [comment]
[Docs](https://open-amt-cloud-toolkit.github.io/docs/2.7/APIs/indexMPS/) have been updated for **1.1** and **1.2**. Also, noticed AuditLogResponse needs to be fixed. Will update that too.

**Comment by graikhel-intel** [comment]
Here is the link to the specification https://www.dmtf.org/sites/default/files/standards/documents/DSP0136.pdf. Check the table on page number 85 (A.7 IPMI 1.0 Entity IDs)

I noticed one discrepancy between the spec and our code with respect to Entity, seems like 35 should be 'Operating system' and not Intel(r) ME. Will work on fixing it.

**Comment by bberbel1-lenovo** [comment]
Great! Thank you for providing the documentation as well.
