### ISSUE TITLE
Incomplete ISecretManagerService definition -- missing 2 methods used in MPS

### ISSUE THREAD

**Issue by bgmckown** [open-amt-cloud-toolkit/mps#828]
**Describe the bug** 🪲

The [`src\interfaces\ISecretManagerService.ts`](https://github.com/open-amt-cloud-toolkit/mps/blob/09bcf1acdf7d6e4c639f0ef0be1b8c469d94481e/src/interfaces/ISecretManagerService.ts) interface appears to be missing at least 2 methods that are referenced in the [`src\utils\certificates.ts`](https://github.com/open-amt-cloud-toolkit/mps/blob/09bcf1acdf7d6e4c639f0ef0be1b8c469d94481e/src/utils/certificates.ts) file. (from the current `main` branch)

- `getMPSCerts()` on [line 25 of `src\utils\certificates.ts`](https://github.com/open-amt-cloud-toolkit/mps/blob/09bcf1acdf7d6e4c639f0ef0be1b8c469d94481e/src/utils/certificates.ts#L25)
- `writeSecretWithObject(...)` on [line 67 of `src\utils\certificates.ts`](https://github.com/open-amt-cloud-toolkit/mps/blob/09bcf1acdf7d6e4c639f0ef0be1b8c469d94481e/src/utils/certificates.ts#L67)

**To Reproduce** 🪜
n/a - discovered via manual code review

**Expected behavior**
Having these functions clearly defined in the `ISecretManagerService` allows them to be cleanly overridden when substituting in a different secrets manager in customized builds.

**Screenshots** 🖼️
 n/a

**AMT Device (please complete the following information):** 🖥️
n/a

**Service Deployment (please complete the following information):** ⛈️
n/a

**Additional context**
n/a

**Comment by bgmckown** [comment]
Tagging @barneytron for visibility

**Comment by madhavilosetty-intel** [comment]
We have a PR later today, Please take a look at it.

**Comment by matt-primrose** [comment]
Resolved with #829
