### ISSUE TITLE
CIRA: Failed to add remote policy access rule

### ISSUE THREAD

**Issue by sakect** [open-amt-cloud-toolkit/mps#847]
**Describe the bug** 🪲
CIRA: Failed to add remote policy access rule

**Expected behavior**
We try to configure and manage the device by AMT feature after follow the step on https://hackmd.io/sLq2LmbDQXGW6p16fGbPyA#Enviroment-Checking it got the device disconnected.
We run the rpc at manage device but it got the message as in below

time="2023-03-20T22:48:10+07:00" level=debug msg="connecting to lms"
time="2023-03-20T22:48:10+07:00" level=debug msg="connected to lms"
time="2023-03-20T22:48:10+07:00" level=debug msg="sending message to LMS"
time="2023-03-20T22:48:10+07:00" level=debug msg="listening for lms messages..."
time="2023-03-20T22:48:10+07:00" level=debug msg="sent message to LMS"
time="2023-03-20T22:48:11+07:00" level=trace msg="done listening"
time="2023-03-20T22:48:11+07:00" level=debug msg="received data from LMS"
time="2023-03-20T22:48:11+07:00" level=trace msg="HTTP/1.1 200 OK\r\nDate: Mon, 20 Mar 2023 22:48:10 GMT\r\nServer: Intel(R) Active Management Technology 14.0.39.1339\r\nX-Frame-Options: DENY\r\nContent-Type: application/soap+xml; charset=UTF-8\r\nTransfer-Encoding: chunked\r\n\r\n0425\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?><a:Envelope xmlns:a=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:b=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns:c=\"http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd\" xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/02/trust\" xmlns:e=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\" xmlns:f=\"http://schemas.dmtf.org/wbem/wsman/1/cimbinding.xsd\" xmlns:g=\"http://schemas.xmlsoap.org/ws/2004/09/enumeration\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><a:Header><b:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</b:To><b:RelatesTo>21</b:RelatesTo><b:Action a:mustUnderstand=\"true\">http://schemas.xmlsoap.org/ws/2004/09/enumeration/PullResponse</b:Action><b:MessageID>uuid:00000000-8086-8086-8086-0000000001F1</b:MessageID><c:ResourceURI>http://intel.com/wbem/wscim/1/amt-schema/1/AMT_ManagementPresenceRemoteSAP</c:ResourceURI></a:Header><a:Body><g:PullResponse><g:Items></g:Items><g:EndOfSequence></g:EndOfSequence></g:PullResponse></a:Body></a:Envelope>\r\n0\r\n\r\n"
time="2023-03-20T22:48:11+07:00" level=debug msg="sending message to RPS"
time="2023-03-20T22:48:11+07:00" level=debug msg="closing connection to lms"
time="2023-03-20T22:48:11+07:00" level=info msg="Status: already enabled in client mode."
time="2023-03-20T22:48:11+07:00" level=info msg="Network: Wired Network Configured. "
time="2023-03-20T22:48:11+07:00" level=info msg="CIRA: Failed to add remote policy access rule"
time="2023-03-20T22:48:11+07:00" level=debug msg="closing connection to lms"

**AMT Device (please complete the following information):** 🖥️
 - OS: Windows 10 IOT
 - AMT Version: Not sure please suggest how to check
 - AMT Configuration Mode: Client Control Mode
 - Network Configuration Dynamic IP 

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: Docker
 - Node Version: Don't know please suggest how to check
 - Component & Version: [e.g. MPS 1.0.0]

**Comment by bwendlandt-intel** [comment]
Hello! Is this still an error that you are seeing during configuration?

**Comment by bwendlandt-intel** [comment]
Stale. No additional information provided.  Please reopen with more detail, if still required. Thanks!
