### ISSUE TITLE
Porting MPS to .NET Core 3.1

### ISSUE THREAD

**Issue by acveigas** [open-amt-cloud-toolkit/mps#9]
Is it possible to port MPS to .NET Core 3.1? Considering that .NET Core 3.1 is an LTS version and is very popular these days?

**Comment by matt-primrose** [comment]
MPS currently runs on Node which has very good cross platform compatibility and a RESTful interface for interacting with the service.  Can you expand on what requirements you have that would drive a port to .NET Core 3.1?

**Comment by acveigas** [comment]
.NET Core is gaining popularity and has ready LTS now. We work predominantly on Microsoft technologies. Having MPS in .NET Core, would help us to integrate it better with our system. .NET Core is a multi-threaded server as well unlike NodeJS. Cross platform support looks great as well. There is also an option of self contained binaries which is why we prefer .NET Core over NodeJS.

**Comment by matt-primrose** [comment]
Porting MPS from Node/TypeScript to .NET Core would be a fairly large undertaking.  For right now, we think it would be better to focus on ensuring that our interfaces are meeting your needs and hopefully the core code implementation would not be an impact to your team using our services.  Look for some new features coming to the MPS that will enhance our Docker and Kubernetes support as well.  This should help to make our MPS micro-service more self-contained and scale-able.
