### ISSUE TITLE
MPS generates new CIRA certs when pre-existing certs are inaccessible

### ISSUE THREAD

**Issue by bgmckown** [open-amt-cloud-toolkit/mps#913]
**Describe the bug** 🪲
Upon first execution, MPS will generate the certificates that it uses for the CIRA connection.
On subsequent executions, it retrieves those certificates from the secrets manager (Vault in the reference design) to use for the duration of that instance's execution.
Since these certificates are pushed to the managed Intel AMT devices during activation, any changes to the certificates would require reactivation of each managed device.

In the current implementation design, if the certs are not retrieved from the secrets manager they are assumed to have not been created and the generation flow is executed. Unfortunately, if there is any issue with retrieving the already defined MPS certificates, then this will also trigger the cert generation flow. For example, in the reference design, if there was an issue with accessing Vault -- whether the vault is sealed or an infrastructure issue -- then the MPS certificates are assumed to not exist and will be regenerated.

This issue appears to be agnostic to the underlying secrets manager implementation, whether Vault or custom middleware.

**To Reproduce** 🪜
1. Initial State: Open AMT Cloud Toolkit, v.2.10, deployed with 1 or more Intel AMT devices activated and connected via CIRA
3. Seal the Vault instance
4. Restart the toolkit services and confirm that CIRA is failing to reconnect

**~Expected~Preferred behavior**
1. The MPS certificate creation process should be done during the deployment stage of the server components (or configurable by users of the toolkit).
2. MPS should log an appropriate error message when the certificates cannot be retrieved from the secrets manager, and then exit.

**Screenshots** 🖼️
n/a

**AMT Device (please complete the following information):** 🖥️
n/a

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: 
 - Node Version: 
 - Component & Version: 

**Additional context**
Related issue: [#614](https://github.com/open-amt-cloud-toolkit/mps/issues/614)

**Comment by matt-primrose** [comment]
In the situation described, MPS will report an unhealthy state via the MPS healthcheck API.  If/when Vault access is restored, then the original certificates will be accessible by MPS and MPS will use those for incoming AMT connections.
